/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AssessmentItem } from "./types";

export const initialAssessments: AssessmentItem[] = [
  // 1. ข้อกำหนดทั่วไป
  {
    Main_Category: "1. ข้อกำหนดทั่วไป",
    Sub_Category: "1.1 การบริหารจัดการทรัพยากรฯ",
    Item_ID: "1.1.1",
    Criteria_Detail: "1. มีแผนผังโครงสร้างองค์กรระดับหน่วยงาน แสดงความเชื่อมโยง ของบุคลากรทั้งหมดภายในหน่วยงานรังสีวินิจฉัยและ/หรือรังสีร่วมรักษา",
    Success_Indicator: "",
    Status: "🟢 พร้อมรับตรวจ",
    Responsible_Person: "",
    Evidence_Link: ["https://drive.google.com/file/d/12pMlANTZ4xml6adlffpMmIfOJH0X6eXq/view?usp=sharing"],
    Auditor_Comment: "",
    Last_Update: "19/5/2026"
  },
  {
    Main_Category: "1. ข้อกำหนดทั่วไป",
    Sub_Category: "1.1 การบริหารจัดการทรัพยากรฯ",
    Item_ID: "1.1.2",
    Criteria_Detail: "2. มีคู่มือคุณภาพ (Quality Manual) ระบุรายละเอียดขององค์กร นโยบายคุณภาพ วิสัยทัศน์ วัตถุประสงค์ ตัวชี้วัดคุณภาพและพันธกิจ ขององค์กร ประกอบด้วยกระบวนการต่างๆ ที่อยู่ในความรับผิดชอบขององค์กร",
    Success_Indicator: "",
    Status: "🟢 พร้อมรับตรวจ",
    Responsible_Person: "",
    Evidence_Link: ["https://docs.google.com/document/d/1Af3vaNd0HA3NTeRKNnGliewEkDXA8fz5oKcKQZCKiR8/edit?usp=drive_link"],
    Auditor_Comment: "",
    Last_Update: "19/5/2026"
  },
  {
    Main_Category: "1. ข้อกำหนดทั่วไป",
    Sub_Category: "1.2 แผนผังการจัดการคุณภาพฯ",
    Item_ID: "1.2.1",
    Criteria_Detail: "มีแผนผังการจัดการคุณภาพในงานรังสีวินิจฉัยและ/หรือรังสีร่วมรักษาที่แสดงให้เห็นความเชื่อมโยงกับการจัดการคุณภาพของหน่วยงานมีการกำหนดหน้าที่ผู้รับผิดชอบ ตามบริบทของสถานพยาบาลหรือโรงพยาบาล (ข้อมูลส่วนนี้แสดงในคู่มือคุณภาพของหน่วยงาน)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },

  // 2. ทรัพยากรบุคคล
  {
    Main_Category: "2. ทรัพยากรบุคคล",
    Sub_Category: "2.1 มีบุคลากรทางด้านวิชาชีพรังสี",
    Item_ID: "2.1.1",
    Criteria_Detail: "มีบุคลากรทางด้านวิชาชีพเพียงพอและปฏิบัติงานได้ตลอดเวลาที่ให้บริการ (ตามบริบทการให้บริการของโรงพยาบาล)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "2. ทรัพยากรบุคคล",
    Sub_Category: "2.2 การกำหนดความรับผิดชอบอำนาจหน้าที่",
    Item_ID: "2.2.1",
    Criteria_Detail: "มีการกำหนดความรับผิดชอบของบุคลากร (Job description) เป็นลายลักษณ์อักษร และมีการทบทวนทุก 1 ปี",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "2. ทรัพยากรบุคคล",
    Sub_Category: "2.3 มีผลการประเมินความสามารถ",
    Item_ID: "2.3.1",
    Criteria_Detail: "มีผลการประเมินของบุคลากรที่ช่วยปฏิบัติงาน ฝ่ายสนับสนุน เช่น ผู้ช่วยนักรังสีฯ พนักงานธุรการ งานทะเบียน (ผ่านเกณฑ์ร้อยละ 80) อย่างน้อยปีละ 1 ครั้ง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "2. ทรัพยากรบุคคล",
    Sub_Category: "2.3 มีผลการประเมินความสามารถ",
    Item_ID: "2.3.2",
    Criteria_Detail: "มีผลการประเมินของบุคลากรที่ช่วยปฏิบัติงาน ฝ่ายบริการ เช่น แม่บ้าน พนักงานทำความสะอาด พนักงานเปล (ผ่านเกณฑ์ร้อยละ 80) อย่างน้อยปีละ 1 ครั้ง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "2. ทรัพยากรบุคคล",
    Sub_Category: "2.4 มีแผนพัฒนาบุคลากร",
    Item_ID: "2.4.1",
    Criteria_Detail: "1. มีแผนพัฒนาบุคลากรในแต่ละปี (สามารถอบรมออนไลน์ได้ และเนื้อหาการฝึกอบรมต้องเหมาะสมกับงานด้านวิชาชีพรังสี ทั้งด้านวิชาการและบริหารจัดการ) และแผนได้รับการอนุมัติ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "2. ทรัพยากรบุคคล",
    Sub_Category: "2.4 มีแผนพัฒนาบุคลากร",
    Item_ID: "2.4.2",
    Criteria_Detail: "2. มีรายงานผลการดำเนินการตามแผน (ดำเนินการไม่น้อยกว่า ร้อยละ 50 ของจำนวนบุคลากรด้านวิชาชีพรังสีทั้งหมด)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "2. ทรัพยากรบุคคล",
    Sub_Category: "2.5 การจัดทำประวัติการฝึกอบรม",
    Item_ID: "2.5.1",
    Criteria_Detail: "มีการจัดทำประวัติการฝึกอบรม ประสบการณ์ และทักษะ ที่จำเป็น ต่อเนื่องและเป็นปัจจุบัน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },

  // 3. อาคาร สถานที่ และสิ่งแวดล้อม
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.1 ความปลอดภัยและการป้องกันอันตรายฯ",
    Item_ID: "3.1.1",
    Criteria_Detail: "หน่วยงานมีนโยบายส่งเสริมในการใช้หลักความปลอดภัยและการ ป้องกันอันตรายจากรังสี 3 ประการ (เวลา ระยะทาง เครื่องกำบัง) มีสื่อแสดงให้เห็นถึงนโยบาย เช่น แผ่นพับ one-page หรือ คลิปสั้น เป็นต้น หรือสอบถามเจ้าหน้าที่ในการปฏิบัติงาน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.2 สถานที่และสิ่งแวดล้อมห้องรังสี",
    Item_ID: "3.2.1",
    Criteria_Detail: "1. ระบบแสงสว่างภายในห้องตรวจผู้ปฏิบัติงานสามารถปิด-เปิด ได้สะดวกขณะปฏิบัติงาน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.2 สถานที่และสิ่งแวดล้อมห้องรังสี",
    Item_ID: "3.2.2",
    Criteria_Detail: "2. ห้องตรวจทางรังสี พื้นที่ลงทะเบียน พื้นที่รอรับบริการ ห้องพักเจ้าหน้าที่ และจุดควบคุมการฉายรังสี (Control booth) มีความสว่างเพียงพอ โดยมีผลการตรวจที่ผ่านตามเกณฑ์มาตรฐานระบบบริการสุขภาพจากหน่วยงานที่รับผิดชอบ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.3 พื้นที่รอรับบริการ",
    Item_ID: "3.3.1",
    Criteria_Detail: "1. มีพื้นที่เพียงพอและการจัดแบ่งพื้นที่เป็นสัดส่วนตามบริบทของ หน่วยบริการ เช่น พื้นที่นั่งรอรับบริการในส่วนการให้บริการทางรังสี ต่างๆ เก้าอี้รอรับบริการ สะอาดและจำนวนเพียงพอ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.3 พื้นที่รอรับบริการ",
    Item_ID: "3.3.2",
    Criteria_Detail: "2. มีอากาศถ่ายเท ภายใต้การควบคุมกำกับของหน่วยควบคุมการติดเชื้อของโรงพยาบาล หรือสอดคล้องกับมาตรการป้องกันการ ติดเชื้อระบบหายใจ (ให้ยึดรายงานผล ENV เป็นหลัก)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.4 ห้องเปลี่ยนเสื้อผ้า",
    Item_ID: "3.4.1",
    Criteria_Detail: "มีห้องเปลี่ยนเสื้อผ้าที่มีความมิดชิด ปลอดภัย และมีอากาศถ่ายเท สะดวก และมีปุ่มหรือสัญญาณให้ผู้รับบริการกดกรณีฉุกเฉิน (กรณีที่ใช้ผ้าม่านกั้นเป็นห้องเปลี่ยนเสื้อผ้าต้องมีการทำแบบประเมินความพึงพอใจ)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.5 บริการตรวจพิเศษด้วยสารเปรียบต่าง",
    Item_ID: "3.5.1",
    Criteria_Detail: "1. มีพื้นที่เตรียมสารเปรียบต่าง (พื้นที่สามารถอยู่ในห้องเอกซเรย์ได้ แต่ตอนเอกซเรย์ให้นำสารเปรียบต่างออกนอกพื้นที่ห้องเอกซเรย์)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.5 บริการตรวจพิเศษด้วยสารเปรียบต่าง",
    Item_ID: "3.5.2",
    Criteria_Detail: "2. กรณีเป็นห้องตรวจพิเศษทางรังสีวินิจฉัยด้วยสารเปรียบต่าง มีห้องสุขาที่อยู่ในห้องตรวจหรือใกล้เคียง มีอุปกรณ์หรือกริ่งสัญญาณขอความช่วยเหลือสำหรับผู้รับบริการ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.6 พื้นที่/ห้องเก็บเครื่องมือและอุปกรณ์",
    Item_ID: "3.6.1",
    Criteria_Detail: "มีพื้นที่/ห้องเก็บเครื่องมือ อุปกรณ์และวัสดุทางรังสี เป็นสัดส่วน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.7 ระบบระบายอากาศตามเกณฑ์",
    Item_ID: "3.7.1",
    Criteria_Detail: "มีรายงานผลการตรวจสอบเป็นไปตามข้อกำหนดทางอาชีวอนามัย และการป้องกันการติดเชื้อของโรงพยาบาล เช่น การระบายอากาศดีไม่มีกลิ่นรบกวน ถังขยะแยกประเภท มีฝาปิด ไม่ส่งกลิ่นรบกวน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.8 สถานที่เตรียมตัวผู้ป่วย",
    Item_ID: "3.8.1",
    Criteria_Detail: "มีสถานที่ในการเตรียมตัวผู้ป่วยรอรับบริการ ในงานทางรังสีวินิจฉัยและ/หรือรังสีร่วมรักษา และ MRI สำหรับเตรียมการตรวจให้กับผู้รับบริการอย่างเหมาะสม เช่น การเปิดเส้น การเตรียมดมยา",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.9 การติดตั้งถังดับเพลิง",
    Item_ID: "3.9.1",
    Criteria_Detail: "มีการติดตั้งถังดับเพลิงที่เหมาะสม พร้อมใช้งานและมีการตรวจสอบอย่างน้อยเดือนละ 1 ครั้ง หรือตามระยะเวลาที่ผู้ผลิตกำหนด ติดป้ายแสดงผลการตรวจสอบ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.10 ป้ายทางหนีไฟ หรือเหตุฉุกเฉิน",
    Item_ID: "3.10.1",
    Criteria_Detail: "1. มีป้ายทางหนีไฟติดตั้งในตำแหน่งที่เหมาะสม และเพียงพอ มองเห็นได้ในที่มืด มีการตรวจสอบและทดสอบประสิทธิภาพ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.10 ป้ายทางหนีไฟ หรือเหตุฉุกเฉิน",
    Item_ID: "3.10.2",
    Criteria_Detail: "2. มีแผนผังเส้นทางอพยพแสดงภายในแผนก",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.11 ป้ายเตือนภัยจากรังสีและสนามแม่เหล็ก",
    Item_ID: "3.11.1",
    Criteria_Detail: "มีป้ายเตือนภัยจากรังสีและสนามแม่เหล็ก และห้องเอกซเรย์ต้องมีสัญญาณไฟที่แสดงสถานะกำลังฉายรังสี ป้ายติดตั้งหน้าห้องรังสีทางการแพทย์ทุกห้อง ใช้ภาษาที่ผู้รับบริการเข้าใจและปฏิบัติตามได้ สัญญาณไฟใช้งานได้",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.12 ป้ายเตือนสตรีมีครรภ์",
    Item_ID: "3.12.1",
    Criteria_Detail: "1. มีป้ายหรือเครื่องหมายเตือนสตรีมีครรภ์ หรือมีโอกาสตั้งครรภ์ ให้แจ้งเจ้าหน้าที่",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "3. อาคาร สถานที่ และสิ่งแวดล้อม",
    Sub_Category: "3.12 ป้ายเตือนสตรีมีครรภ์",
    Item_ID: "3.12.2",
    Criteria_Detail: "2. สามารถใช้ภาษาต่างๆ ร่วมกับรูปภาพ สื่อให้ผู้รับบริการเข้าใจและปฏิบัติตามได้",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },

  // 4. เครื่องมือ และอุปกรณ์
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.1 มาตรฐานเครื่องมือทางรังสีวิทยา",
    Item_ID: "4.1.1",
    Criteria_Detail: "กรณีที่ 1: มีรายงานผลการตรวจสอบคุณภาพที่ผ่านมาตรฐาน โดยหน่วยงานที่ได้รับการรับรองมาตรฐานระบบ ISO/IEC 17025 ทุก 2 ปี (หรือมีหลักฐานสำเนาหนังสือแจ้งขอรับการทดสอบล่วงหน้าไม่น้อยกว่า 1 เดือน)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.1 มาตรฐานเครื่องมือทางรังสีวิทยา",
    Item_ID: "4.1.2",
    Criteria_Detail: "กรณีที่ 2: เครื่องเสีย หรือมีเหตุสุดวิสัย ให้แสดงบันทึกประวัติของเครื่องนั้นๆ ให้เห็นเป็นหลักฐานชัดเจน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.1 มาตรฐานเครื่องมือทางรังสีวิทยา",
    Item_ID: "4.1.3",
    Criteria_Detail: "กรณีที่ 3: หากเปลี่ยนหลอดเอกซเรย์ มีรายงานผลการตรวจสอบคุณภาพที่ผ่านมาตรฐานระบบ ISO/IEC 17025",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.1 มาตรฐานเครื่องมือทางรังสีวิทยา",
    Item_ID: "4.1.4",
    Criteria_Detail: "กรณีเครื่องอัลตราซาวด์: มีรายงานผลการตรวจสอบคุณภาพ หรือผลการบำรุงรักษา (maintenance) ที่กลุ่มงานรังสีวิทยา ดำเนินการ หรือมีการควบคุมคุณภาพตามมาตรฐาน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.1 มาตรฐานเครื่องมือทางรังสีวิทยา",
    Item_ID: "4.1.5",
    Criteria_Detail: "กรณีจ้างเหมาบริการ (outsource): มีระบบการติดตามตรวจสอบคุณภาพให้เป็นไปตามมาตรฐานความปลอดภัยทางรังสีและมาตรฐานคุณภาพห้องปฏิบัติการรังสีวินิจฉัย กระทรวงสาธารณสุข",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.2 การขออนุญาตแจ้งการครอบครอง",
    Item_ID: "4.2.1",
    Criteria_Detail: "1. มีใบรับแจ้งอนุญาตครอบครองหรือใช้เครื่องกำเนิดรังสีเพื่อการวินิจฉัยทางการแพทย์ ตามกฎกระทรวง พ.ศ.2566",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.2 การขออนุญาตแจ้งการครอบครอง",
    Item_ID: "4.2.2",
    Criteria_Detail: "2. หากกรณีที่อยู่ในช่วงดำเนินการขอใบรับแจ้ง ให้แสดงเอกสารหรือหนังสือรับรองอยู่ในช่วงดำเนินการ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.3 อุปกรณ์ป้องกันรังสี",
    Item_ID: "4.3.1",
    Criteria_Detail: "1. มีอุปกรณ์ป้องกันรังสีเพียงพอ ตามที่กำหนด สะอาด มีสภาพพร้อมใช้งาน และสามารถป้องกันรังสีได้",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.3 อุปกรณ์ป้องกันรังสี",
    Item_ID: "4.3.2",
    Criteria_Detail: "2. ห้อง MRI ให้มีอุปกรณ์ตามเกณฑ์กำหนด",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.3 อุปกรณ์ป้องกันรังสี",
    Item_ID: "4.3.3",
    Criteria_Detail: "3. มีการตรวจสอบคุณภาพเสื้อตะกั่ว และหารอยแตกของเสื้อตะกั่วด้วยรังสีเอกซ์ ทุก 6 เดือน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.4 อุปกรณ์ประกอบการให้บริการ",
    Item_ID: "4.4.1",
    Criteria_Detail: "พร้อมใช้งาน สะอาด ไม่ชำรุด มีรายงานผลการตรวจสอบคุณภาพตามชนิดเครื่องมือ/อุปกรณ์ เช่น Injector, EKG, เครื่องจับ O2 Sat, set emergency, อุปกรณ์รัดตรึงผู้ป่วย และเครื่องวัดความดัน BP",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.4 อุปกรณ์ประกอบการให้บริการ",
    // Wait, 4.5 starts here
    Item_ID: "4.5.1",
    Criteria_Detail: "1. มีเอกสารคู่มือการใช้งานเครื่องมือ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.5 คู่มือการใช้งานและประวัติบำรุงรักษา",
    Item_ID: "4.5.2",
    Criteria_Detail: "2. มีเอกสารบันทึกประวัติการบำรุงรักษา (Preventive maintenance) หรือซ่อมบำรุง (Corrective maintenance) อย่างต่อเนื่อง เป็นปัจจุบัน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.5 คู่มือการใช้งานและประวัติบำรุงรักษา",
    Item_ID: "4.5.3",
    Criteria_Detail: "3. มีแผนการตรวจสอบและเตรียมความพร้อมของเครื่องมือ/อุปกรณ์ พร้อมแสดงผลการดำเนินการ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.6 อุปกรณ์ในการเคลื่อนย้ายผู้ป่วย",
    Item_ID: "4.6.1",
    Criteria_Detail: "สะอาด เพียงพอ และพร้อมใช้งาน สภาพดี มีจำนวนเพียงพอ (สามารถใช้ร่วมกับแผนกที่อยู่บริเวณใกล้เคียงได้)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.7 เสื้อผ้าสำหรับผู้รับบริการ",
    Item_ID: "4.7.1",
    Criteria_Detail: "1. มีเสื้อผ้าเพียงพอกับจำนวนผู้ป่วยในแต่ละวัน สภาพดี มีที่จัดเก็บแยกก่อนและหลังใช้งาน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.7 เสื้อผ้าสำหรับผู้รับบริการ",
    Item_ID: "4.7.2",
    Criteria_Detail: "2. ถังใส่เสื้อผ้าที่ใช้แล้ว มีฝาปิดมิดชิด ไม่ใช้ซ้ำ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.7 เสื้อผ้าสำหรับผู้รับบริการ",
    Item_ID: "4.7.3",
    Criteria_Detail: "3. มีการปฏิบัติตามมาตรฐานหลักการป้องกันการติดเชื้อและควบคุมการแพร่กระจายเชื้อในโรงพยาบาล (Precautions/Universal Precautions)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.8 การทำความสะอาดเครื่องมือ/อุปกรณ์",
    Item_ID: "4.8.1",
    Criteria_Detail: "1. ตรวจสอบตามแนวปฏิบัติของหน่วยงาน ตามมาตรฐานหลักการป้องกันการติดเชื้อและควบคุมการแพร่กระจายเชื้อในโรงพยาบาล",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "4. เครื่องมือ และอุปกรณ์",
    Sub_Category: "4.8 การทำความสะอาดเครื่องมือ/อุปกรณ์",
    Item_ID: "4.8.2",
    Criteria_Detail: "2. ตรวจสอบความสะอาดของเครื่องมือ/อุปกรณ์ มีการจัดการป้องกันการติดเชื้อ เช่น ผ้าคลุม ผ้ารองศีรษะ เปลี่ยนให้กับผู้รับบริการรายต่อราย สำหรับงานรังสีรักษา หรือตามบริบท",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },

  // 5. ความปลอดภัย และการบริหารจัดการความเสี่ยง
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.1 อุปกรณ์วัดรังสีบุคคล (OSL)",
    Item_ID: "5.1.1.1",
    Criteria_Detail: "1. ผู้ปฏิบัติงานทางรังสีทุกคนมีอุปกรณ์วัดรังสีบุคคล มีการใช้งานที่ถูกต้อง ต่อเนื่องเป็นปัจจุบัน (ใช้งาน 1 คน/1 เครื่อง ไม่ใช้ร่วมกัน)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.1 อุปกรณ์วัดรังสีบุคคล (OSL)",
    Item_ID: "5.1.1.2",
    Criteria_Detail: "2. มีการจัดเก็บ สรุปผล และวิเคราะห์ข้อมูลรังสีสะสมรายบุคคล ระยะ 1 ปี และ 5 ปี ของผู้ปฏิบัติงานทางรังสี พร้อมทั้งรายงานผลให้ผู้ปฏิบัติงานทราบ และนำเสนอผู้บริหาร",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.1 อุปกรณ์วัดรังสีบุคคล (OSL)",
    Item_ID: "5.1.1.3",
    Criteria_Detail: "3. กรณีปริมาณรังสีเกิน มีการกำหนดแนวทางปฏิบัติที่ระบุแนวทางการแก้ไข อย่างชัดเจน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.1 อุปกรณ์วัดรังสีบุคคล (OSL)",
    Item_ID: "5.1.1.4",
    Criteria_Detail: "4. มีการดำเนินการทุกหน่วยงานที่เกี่ยวข้องกับการใช้รังสี",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.2 ตารางเทคนิคการให้ปริมาณรังสี",
    Item_ID: "5.1.2.1",
    Criteria_Detail: "มีตารางหรือคู่มือที่แสดง Technical chart หรือโปรแกรมที่มีการตั้งค่าเทคนิค ตรงกับที่ระบุไว้ หรือเทียบเท่า โดยมีการทบทวน ทุก 1 ปี",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.3 การฟื้นฟูความรู้เรื่องการป้องกันรังสี",
    Item_ID: "5.1.3.1",
    Criteria_Detail: "1. รายงานการฝึกอบรมเรื่องการป้องกันอันตรายจากรังสีสำหรับ ผู้ปฏิบัติงานด้านรังสี อย่างน้อย 3 ปี ต่อครั้ง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.3 การฟื้นฟูความรู้เรื่องการป้องกันรังสี",
    Item_ID: "5.1.3.2",
    Criteria_Detail: "2. มีรายงาน หรือเอกสารที่ให้ความรู้แก่ผู้ปฏิบัติงานที่เกี่ยวข้องกับงานรังสี",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.4 การอบรมและการซ้อมแผนอัคคีภัยฯ",
    Item_ID: "5.1.4.1",
    Criteria_Detail: "1. มีแผนการดำเนินการในกรณีเกิดเหตุฉุกเฉิน และมีการทบทวน หรือปรับปรุงแผนฯ ตามรอบเวลาที่หน่วยงานกำหนด อย่างน้อยปีละ 1 ครั้ง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.4 การอบรมและการซ้อมแผนอัคคีภัยฯ",
    Item_ID: "5.1.4.2",
    Criteria_Detail: "2. มีรายงานหลักฐาน การจัดอบรมและการซ้อมแผน/หรือการเตรียมรับมือ ด้านอัคคีภัย/ภัยธรรมชาติ หรืออุบัติเหตุทางรังสี อย่างน้อยปีละ 1 ครั้ง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.1.5 วัสดุและเวชภัณฑ์ด้านความปลอดภัย",
    Item_ID: "5.1.5.1",
    Criteria_Detail: "มีวัสดุและเวชภัณฑ์ด้านความปลอดภัยให้กับผู้ปฏิบัติงาน เช่น หน้ากากอนามัย ถุงมือ ผ้ากันเปื้อน น้ำยาล้างมือ น้ำยาทำความ สะอาด พร้อมที่จัดเก็บที่สะอาดและเป็นระเบียบ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.1 ระบบการเฝ้าระวังและดูแลผู้รับบริการ",
    Item_ID: "5.2.1.1",
    Criteria_Detail: "มีระบบหรือแนวทางการเฝ้าระวังดูแลผู้รับบริการ รวมถึงการ เคลื่อนย้าย รับส่งต่อผู้รับบริการ ผู้ป่วยภาวะวิกฤติต้องมีเจ้าหน้าที่ ดูแลอย่างเหมาะสมสอดคล้องกับแนวทางปฏิบัติของโรงพยาบาล",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.2 การฝึกอบรมการดูแลเคลื่อนย้ายผู้ป่วย",
    Item_ID: "5.2.2.1",
    Criteria_Detail: "1. มีอุปกรณ์ในการเคลื่อนย้าย เช่น แผ่น slide board ที่สามารถนำมาใช้งานได้ทันที",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.2 การฝึกอบรมการดูแลเคลื่อนย้ายผู้ป่วย",
    Item_ID: "5.2.2.2",
    Criteria_Detail: "2. มีคู่มือให้ความรู้ในการดูแลและเคลื่อนย้ายผู้รับบริการ มีรายงานการให้ความรู้/อบรม ในการดูแลและเคลื่อนย้ายผู้รับบริการของบุคลากรในแผนก (อย่างน้อยปีละ 1 ครั้ง)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.3 เส้นทางการเคลื่อนย้ายผู้รับบริการ",
    Item_ID: "5.2.3.1",
    Criteria_Detail: "มีป้ายเส้นทาง มีทางลาด ราวจับ และผู้รับบริการที่ต้องใช้อุปกรณ์พิเศษ สามารถเข้ารับการบริการตรวจได้อย่างสะดวกและปลอดภัยตามบริบทของโรงพยาบาล สะดวก ไม่มีสิ่งกีดขวาง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.4 ระบบการจัดการความเสี่ยง (Risk)",
    Item_ID: "5.2.4.1",
    Criteria_Detail: "1. มีบัญชีความเสี่ยง (Risk Profile) พร้อมนำเสนอมาตรการป้องกันการเกิดอุบัติการณ์ ให้ครอบคลุมด้านตั้งครรภ์ การใช้สารเปรียบต่าง การติดเชื้อ และการได้รับปริมาณรังสีเกินความจำเป็น",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.4 ระบบการจัดการความเสี่ยง (Risk)",
    Item_ID: "5.2.4.2",
    Criteria_Detail: "2. มีบันทึกหรือระบบรายงานอุบัติการณ์",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.4 ระบบการจัดการความเสี่ยง (Risk)",
    Item_ID: "5.2.4.3",
    Criteria_Detail: "3. มีแผนการจัดการความเสี่ยง ติดตาม รายงานผลการจัดการความเสี่ยงประจำปี",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.5 การทวนสอบผู้รับบริการในวัยเจริญพันธุ์",
    Item_ID: "5.2.5.1",
    Criteria_Detail: "1. มีแนวทางปฏิบัติ และการทวนสอบผู้รับบริการในวัยเจริญพันธุ์ถึงโอกาสในการตั้งครรภ์ทุกครั้ง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.5 การทวนสอบผู้รับบริการในวัยเจริญพันธุ์",
    Item_ID: "5.2.5.2",
    Criteria_Detail: "2. มีเอกสารหลักฐานยินยอมในกรณีที่ผู้รับบริการตั้งครรภ์ และมีแนวทางปฏิบัติในกรณีต้องให้บริการเอกซเรย์สตรีมีครรภ์",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.6 แนวทางปฏิบัติกรณีเกิดเหตุฉุกเฉิน",
    Item_ID: "5.2.6.1",
    Criteria_Detail: "1. มีแนวทางปฏิบัติ/คู่มือการปฏิบัติงาน กรณีเกิดเหตุฉุกเฉินต่างๆ หรือเหตุตามความเสี่ยง ขณะให้บริการ หรืออยู่ในพื้นที่ มีการกำหนดรหัสฉุกเฉิน (emergency code)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.6 แนวทางปฏิบัติกรณีเกิดเหตุฉุกเฉิน",
    Item_ID: "5.2.6.2",
    Criteria_Detail: "2. รายงานการซ้อมแผน/การเข้าร่วมการซ้อมแผนของสถาบัน/โรงพยาบาล (เหตุฉุกเฉินทั่วไป เช่นผู้รับบริการหมดสติ ผู้รับบริการได้รับอุบัติเหตุขณะให้บริการ)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.2.7 การคัดกรองผู้รับบริการเสี่ยงสูง/MRI",
    Item_ID: "5.2.7.1",
    Criteria_Detail: "มีแนวทางการปฏิบัติ และคู่มือการคัดกรอง การแนะนำญาติ และผู้รับบริการที่มีความเสี่ยงสูง รวมถึงเครื่องตรวจสนามแม่เหล็กแรงสูง (MRI)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.1 บริการตรวจพิเศษโดยใช้สารเปรียบต่าง",
    Item_ID: "5.3.1.1",
    Criteria_Detail: "มีแนวทางปฏิบัติ/คู่มือ หรือระบบการนัดผู้รับบริการ มีการอธิบายและให้คำแนะนำที่จำเป็นและมีกระบวนการในการติดตามผู้รับบริการเพื่อรับการตรวจพิเศษทางรังสีตามนัด",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.2 การทวนสอบความเข้าใจขั้นตอนการตรวจ",
    Item_ID: "5.3.2.1",
    Criteria_Detail: "มีแนวทางปฏิบัติ/คู่มือ ขั้นตอนการตรวจพิเศษทางรังสี และมีการ ทวนสอบความเข้าใจของผู้รับบริการเกี่ยวกับขั้นตอนและข้อปฏิบัติก่อน-หลังการตรวจ จนสามารถปฏิบัติได้ถูกต้อง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.3 การใช้สารเปรียบต่างภายใต้การกำกับ",
    Item_ID: "5.3.3.1",
    Criteria_Detail: "มีแนวทางการปฏิบัติงานการตรวจพิเศษทางรังสี ที่มีการใช้สาร เปรียบต่าง ภายใต้การกำกับดูแลของผู้ประกอบวิชาชีพเวชกรรมผู้สั่งตรวจ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.4 หลักฐานการคัดกรองผู้รับบริการเสี่ยงสูง",
    Item_ID: "5.3.4.1",
    Criteria_Detail: "มีบันทึกการคัดกรองผู้รับบริการที่มีความเสี่ยงสูง กรณีที่มีการใช้สารเปรียบต่าง (เช่น ผลการตรวจทางห้องปฏิบัติการ Lab)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.5 การวัดสัญญาณชีพ (Vital sign)",
    Item_ID: "5.3.5.1",
    Criteria_Detail: "มีรายงานการวัดสัญญาณชีพ (Vital sign) ก่อน ระหว่าง และ/หรือ หลังการรับบริการตรวจวินิจฉัย หรือการรักษาทางรังสีวิทยา ที่เหมาะสมตามชนิดและประเภทของการตรวจฯ ซึ่งระบุไว้ในแต่ละ protocol",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.6 อาการไม่พึงประสงค์จากสารเปรียบต่าง",
    Item_ID: "5.3.6.1",
    Criteria_Detail: "1. มีแนวทางปฏิบัติ/คู่มือการปฏิบัติงาน กรณีเกิดเหตุผู้รับบริการมีอาการไม่พึงประสงค์จากการได้รับสารเปรียบต่าง ทั้งในและนอกเวลาทำการ มีการกำหนดรหัสฉุกเฉิน (emergency code)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.6 อาการไม่พึงประสงค์จากสารเปรียบต่าง",
    Item_ID: "5.3.6.2",
    Criteria_Detail: "2. รายงานการซ้อมแผน อย่างน้อยปีละ 1 ครั้ง (แผนผู้รับบริการแพ้สารเปรียบต่าง หรือเกิดเหตุการณ์ไม่พึงประสงค์)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.7 การดูแลผู้ป่วยทางหัตถการรังสี",
    Item_ID: "5.3.7.1",
    Criteria_Detail: "ให้มีแนวทาง /คู่มือและอุปกรณ์ที่จำเป็นในการดูแลผู้ป่วยทางหัตถการรังสีจากการให้บริการ (Intervention Radiology)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.3.8 ควบคุมคุณภาพวัสดุเวชภัณฑ์สารเปรียบต่าง",
    Item_ID: "5.3.8.1",
    Criteria_Detail: "มีบันทึกวันหมดอายุและบันทึกการเบิกจ่ายพัสดุที่เป็นปัจจุบัน มีการจัดเก็บที่ถูกต้องเหมาะสมมีคุณภาพตามคู่มือบริษัท ไม่หมดอายุ ไม่เสื่อมสภาพ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.1 ระบบป้องกันอันตรายจากรังสี (เจ้าหน้าที่)",
    Item_ID: "5.4.1.1",
    Criteria_Detail: "มีคู่มือ/แนวทางการป้องกันอันตรายสำหรับผู้ปฏิบัติงานด้านรังสี",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.2 ระบบป้องกันอันตรายจากเครื่อง MRI",
    Item_ID: "5.4.2.1",
    Criteria_Detail: "มีระบบจัดการเครื่องเอ็มอาร์ไอเมื่อเกิดเหตุฉุกเฉิน: 1. มีระบบปิดสนามแม่เหล็กแบบตัวนำยิ่งยวด (Emergency field shut down unit) หรือ 2. ระบบในการหยุดความเป็นสนามเหล็กของเครื่อง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.3 ประเมินค่าปริมาณรังสีที่ผู้ป่วยได้รับ",
    Item_ID: "5.4.3.1",
    Criteria_Detail: "มีรายงานการประเมินค่าปริมาณรังสีที่ใช้ถ่ายภาพรังสีเปรียบเทียบกับค่าปริมาณรังสีอ้างอิง (DRLs) ของประเทศที่เป็นปัจจุบัน (ทุก 2 ปี หรือมีการเปลี่ยนเครื่อง/เปลี่ยนหลอดเอกซเรย์)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.4 กระบวนการป้องกันการติดเชื้อ (IC)",
    Item_ID: "5.4.4.1",
    Criteria_Detail: "1. มีคู่มือ/แนวการป้องกันการติดเชื้อและการแพร่กระจายเชื้อ ครอบคลุมตามมาตรฐาน การป้องกันการติดเชื้อ หรือระบบ IC ของหน่วยงานและโรงพยาบาล",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.4 กระบวนการป้องกันการติดเชื้อ (IC)",
    Item_ID: "5.4.4.2",
    Criteria_Detail: "2. มีบันทึก/รายงานการให้ความรู้การป้องกันการติดเชื้อและการ แพร่กระจายเชื้อ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.4 กระบวนการป้องกันการติดเชื้อ (IC)",
    Item_ID: "5.4.4.3",
    Criteria_Detail: "3. มีวิธีการแนวทางจัดการของเสียที่เกิดจาก ขยะติดเชื้อ ของมีคม",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.4 กระบวนการป้องกันการติดเชื้อ (IC)",
    Item_ID: "5.4.4.4",
    Criteria_Detail: "4. มีวัสดุการป้องกันการติดเชื้อ โรคระบบทางเดินหายใจ ติดเชื้อ ทางผิวสัมผัส และโรคติดเชื้อ ในกระแสเลือด",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.5 การป้องกันรังสีให้ญาติ/ผู้ติดตาม",
    Item_ID: "5.4.5.1",
    Criteria_Detail: "มีคู่มือ/แนวทางการป้องกันอันตรายจากรังสีให้กับผู้รับบริการ รวมทั้งญาติหรือผู้ช่วยเหลือผู้รับบริการ รวมทั้งมีอุปกรณ์ป้องกัน อันตรายจากรังสี (เช่น เสื้อยางผสมตะกั่ว)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.6 มาตรการในการช่วยฟื้นคืนชีพ (CPR)",
    Item_ID: "5.4.6.1",
    Criteria_Detail: "1. มีวิธีปฏิบัติหรืออุปกรณ์และยาที่เกี่ยวข้องในการช่วยฟื้นคืนชีพ อย่างมีประสิทธิภาพ ตามบริบทของโรงพยาบาล",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.6 มาตรการในการช่วยฟื้นคืนชีพ (CPR)",
    Item_ID: "5.4.6.2",
    Criteria_Detail: "2. บันทึก/รายงานการฝึกอบรมการช่วยฟื้นคืนชีพ อย่างน้อยปีละ 1 ครั้ง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.7 ระบบไฟฟ้าสำรองส่องสว่างฉุกเฉิน",
    Item_ID: "5.4.7.1",
    Criteria_Detail: "1. มีระบบไฟฟ้าสำรองเพื่อให้แสงสว่างฉุกเฉิน กรณีไฟดับแล้วแสงสว่าง ณ จุดติดตั้ง ส่องสว่างถึงห้องเอกซเรย์ อย่างน้อย 1 จุด",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.7 ระบบไฟฟ้าสำรองส่องสว่างฉุกเฉิน",
    Item_ID: "5.4.7.2",
    Criteria_Detail: "2. มีบันทึกการตรวจสอบระบบไฟฟ้าสำรอง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "5. ความปลอดภัย และการบริหารจัดการความเสี่ยง",
    Sub_Category: "5.4.8 มีกล้องวงจรปิด และ Intercom",
    Item_ID: "5.4.8.1",
    Criteria_Detail: "มีระบบกล้องวงจรปิด และ Intercom ที่สามารถทำการตรวจสอบโดยการมองเห็นและได้ยินในห้องตรวจ CT และห้องตรวจ MRI ตามบริบทการให้บริการ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },

  // 6. การประกันคุณภาพ
  {
    Main_Category: "6. การประกันคุณภาพ",
    Sub_Category: "6.1 แผนและขั้นตอนควบคุมคุณภาพเครื่องมือ",
    Item_ID: "6.1.1",
    Criteria_Detail: "1. มีแผนการควบคุมคุณภาพเครื่องมือครอบคลุมทุกรายการตาม มาตรฐานเครื่องมือแต่ละชนิด มีแผนการควบคุมคุณภาพเครื่องมือในห้องปฏิบัติการ ประกอบด้วยรายการที่ทดสอบ ระยะเวลาและผู้รับผิดชอบ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "6. การประกันคุณภาพ",
    Sub_Category: "6.1 แผนและขั้นตอนควบคุมคุณภาพเครื่องมือ",
    Item_ID: "6.1.2",
    Criteria_Detail: "2. มีแผนการบำรุงรักษาระบบสารสนเทศงานรังสี (PACS)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "6. การประกันคุณภาพ",
    Sub_Category: "6.1 แผนและขั้นตอนควบคุมคุณภาพเครื่องมือ",
    Item_ID: "6.1.3",
    Criteria_Detail: "3. มีแนวทางแก้ไขกรณีผลการทดสอบอยู่นอกเกณฑ์การยอมรับ หรือมีแผนจัดหาทดแทน ในกรณีเครื่องมือชำรุด ไม่สามารถซ่อมได้",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "6. การประกันคุณภาพ",
    Sub_Category: "6.2 ระบบควบคุมคุณภาพโดยนักรังสีเทคนิค",
    Item_ID: "6.2.1",
    Criteria_Detail: "1. มีผลการควบคุมคุณภาพเครื่องมือทางรังสีวิทยา มีแบบบันทึก และรายงานผลการควบคุมคุณภาพและแนวทางการแก้ไขกรณีผล การทดสอบอยู่นอกเกณฑ์การยอมรับ ตามคู่มือ พ.ศ. 2565 (ตรวจขั้นต่ำปีละ 1 ครั้ง ข้อย่อย 6.2.1 - 6.2.7)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "6. การประกันคุณภาพ",
    Sub_Category: "6.2 ระบบควบคุมคุณภาพโดยนักรังสีเทคนิค",
    Item_ID: "6.2.2",
    Criteria_Detail: "2. มีผลการบำรุงรักษาระบบสารสนเทศงานรังสี (PACS) อย่างน้อย ปีละ 2 ครั้ง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "6. การประกันคุณภาพ",
    Sub_Category: "6.3 วิเคราะห์คุณภาพภาพถ่าย อัตราถ่ายซ้ำ",
    Item_ID: "6.3.1",
    Criteria_Detail: "1. มีเอกสารวิเคราะห์สาเหตุอัตราการถ่ายภาพรังสีซ้ำ พร้อมแนวทางในการแก้ไขปัญหาตามสาเหตุนั้นๆอย่างชัดเจน ทุก 3 เดือน (ทั่วไปไม่เกินร้อยละ 8, เต้านมไม่เกินร้อยละ 3)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "6. การประกันคุณภาพ",
    Sub_Category: "6.3 วิเคราะห์คุณภาพภาพถ่าย อัตราถ่ายซ้ำ",
    Item_ID: "6.3.2",
    Criteria_Detail: "2. นำเสนออัตราการถ่ายภาพรังสีซ้ำในรูปแบบของ กราฟ เพื่อแสดง แนวโน้มคุณภาพการบริการ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "6. การประกันคุณภาพ",
    Sub_Category: "6.3 วิเคราะห์คุณภาพภาพถ่าย อัตราถ่ายซ้ำ",
    Item_ID: "6.3.3",
    Criteria_Detail: "3. ในกรณีที่ไม่สามารถแก้ไขให้ไม่เกินร้อยละ 8 ได้ ให้อธิบายเหตุผลประกอบ และมีแผนดำเนินการพัฒนาแก้ไข อย่างสม่ำเสมอ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },

  // 7. การควบคุมเอกสาร
  {
    Main_Category: "7. การควบคุมเอกสาร",
    Sub_Category: "7.1 การจัดทำเอกสารคุณภาพในหน่วยงาน",
    Item_ID: "7.1.1",
    Criteria_Detail: "1. มีแนวทางการจัดทำเอกสารคุณภาพของหน่วยงาน มีการแยก ประเภทเอกสารคุณภาพ เช่น WI (Work Instruction), SOP (Standard Operating Procedure), Good Practice เป็นต้น",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: "19/5/2026"
  },
  {
    Main_Category: "7. การควบคุมเอกสาร",
    Sub_Category: "7.1 การจัดทำเอกสารคุณภาพในหน่วยงาน",
    Item_ID: "7.1.2",
    Criteria_Detail: "2. มีการปรับปรุงเอกสารคุณภาพให้เป็นปัจจุบัน",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "7. การควบคุมเอกสาร",
    Sub_Category: "7.1 การจัดทำเอกสารคุณภาพในหน่วยงาน",
    Item_ID: "7.1.3",
    Criteria_Detail: "3. มีทะเบียนคุมเอกสารคุณภาพของหน่วยงาน และมีการจัดเก็บ เอกสารคุณภาพเป็นระเบียบ สามารถสืบค้น ใช้งานได้สะดวก",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "7. การควบคุมเอกสาร",
    Sub_Category: "7.2 การจัดเก็บและทำลายข้อมูลทางรังสี",
    Item_ID: "7.2.1",
    Criteria_Detail: "มีระเบียบปฏิบัติเกี่ยวกับ การจัดเก็บข้อมูลทางรังสีของผู้รับบริการ แผนการรักษา และเมื่อถึงกำหนดมีการทำลายอย่างถูกต้อง (ใบขอตรวจ, จานแสง PACS, ใบยินยอม, ใบขอประวัติ)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "7. การควบคุมเอกสาร",
    Sub_Category: "7.3 การป้องกันการเข้าถึงไฟล์ระบบ PACS",
    Item_ID: "7.3.1",
    Criteria_Detail: "1. มีที่จัดเก็บข้อมูลผู้รับบริการและการกำหนดสิทธิ์ในการเข้าถึง ข้อมูล/ระบบ PACs",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "7. การควบคุมเอกสาร",
    Sub_Category: "7.3 การป้องกันการเข้าถึงไฟล์ระบบ PACS",
    Item_ID: "7.3.2",
    Criteria_Detail: "2. มีระเบียบปฏิบัติในการป้องกันข้อมูลความลับผู้รับบริการและ การกำหนดสิทธิ์ในการเข้าถึงข้อมูล/ระบบ PACs โดยกำหนดระดับการเข้าถึงข้อมูล ป้องกันการรั่วไหลของข้อมูล",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "7. การควบคุมเอกสาร",
    Sub_Category: "7.3 การป้องกันการเข้าถึงไฟล์ระบบ PACS",
    Item_ID: "7.3.3",
    Criteria_Detail: "3. มีระเบียบปฏิบัติในการขอข้อมูลผู้รับบริการ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "7. การควบคุมเอกสาร",
    Sub_Category: "7.3 การป้องกันการเข้าถึงไฟล์ระบบ PACS",
    Item_ID: "7.3.4",
    Criteria_Detail: "4. มีการสำรองข้อมูลภาพถ่ายรังสีของผู้รับบริการ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },

  // 8. การส่งต่อข้อมูล และการรายงานผล
  {
    Main_Category: "8. การส่งต่อข้อมูล และการรายงานผล",
    Sub_Category: "8.1 ใบขอส่งตรวจ (request)",
    Item_ID: "8.1.1",
    Criteria_Detail: "มีใบขอส่งตรวจ (request) ที่ส่งให้เจ้าหน้าที่รังสี หรือระบบเอกสาร ลงทะเบียนการให้บริการทางรังสี มีข้อระบุบ่งชี้ถึงความ เหมาะสม/ความสมเหตุสมผลของการขอส่งตรวจ และสามารถทวนสอบได้",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "8. การส่งต่อข้อมูล และการรายงานผล",
    Sub_Category: "8.2 การแยกประเภทผู้รับบริการตามลำดับ",
    Item_ID: "8.2.1",
    Criteria_Detail: "มีแนวทางปฏิบัติการเข้ารับบริการตามลำดับความสำคัญของผู้รับบริการแต่ละประเภท และมีการส่งต่อ สื่อสาร ผู้มารับบริการอย่างมีประสิทธิภาพ เช่น ผู้รับบริการที่ต้องได้รับบริการเร่งด่วน หรือเสี่ยงการติดเชื้อ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "8. การส่งต่อข้อมูล และการรายงานผล",
    Sub_Category: "8.3 การควบคุมและคุ้มครองข้อมูล (PDPA)",
    Item_ID: "8.3.1",
    Criteria_Detail: "มีการกำหนดแนวทางปฏิบัติในการควบคุมและคุ้มครองข้อมูลผู้รับบริการด้านรังสีการแพทย์ให้เป็นไปตาม พรบ.คุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA) ครอบคลุมไฟล์ภาพ, ผลวินิจฉัย และข้อมูลโรงพยาบาล",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "8. การส่งต่อข้อมูล และการรายงานผล",
    Sub_Category: "8.4 ควบคุมคุณภาพภาพถ่ายก่อนส่งมอบ",
    Item_ID: "8.4.1",
    Criteria_Detail: "มีแนวทางปฏิบัติ หรือคู่มือในการตรวจสอบคุณภาพภาพถ่ายทางรังสีก่อนส่งมอบ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },

  // 9. การตรวจติดตามภายใน และการประเมินผล
  {
    Main_Category: "9. การตรวจติดตามภายใน และการประเมินผล",
    Sub_Category: "9.1 การทบทวนระบบบริหารคุณภาพ",
    Item_ID: "9.1.1",
    Criteria_Detail: "1. มีรายงานหรือสรุปผลการทบทวนระบบบริหารคุณภาพ (management review) ประกอบด้วยข้อมูลอย่างน้อย ได้แก่ 1.1 ผล Internal audit ทุก 1 ปี, 1.2 ข้อมูลตัวชี้วัด (ร้อยละถ่ายซ้ำ, ผลวัดรังสีสะสมเกินเกณฑ์, ความพึงพอใจ), 1.3 สรุปผลนวัตกรรม, 1.4 ผลทบทวนความเสี่ยง",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "9. การตรวจติดตามภายใน และการประเมินผล",
    Sub_Category: "9.1 การทบทวนระบบบริหารคุณภาพ",
    Item_ID: "9.1.2",
    Criteria_Detail: "2. ห้องปฏิบัติการนำข้อมูลสรุปผลการทบทวนระบบบริหารคุณภาพ (management review) มาปรับปรุง แก้ไข เพื่อให้เกิดการพัฒนาคุณภาพ",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "9. การตรวจติดตามภายใน และการประเมินผล",
    Sub_Category: "9.1 การทบทวนระบบบริหารคุณภาพ",
    Item_ID: "9.1.3",
    Criteria_Detail: "3. มีการทำแผนพัฒนาปรับปรุงอย่างต่อเนื่อง โดยใช้ข้อมูลจากการทบทวนระบบบริหารคุณภาพ และมีการติดตามการดำเนินการให้เป็นไปตามเป้าหมายที่กำหนด",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  },
  {
    Main_Category: "9. การตรวจติดตามภายใน และการประเมินผล",
    Sub_Category: "9.1 การทบทวนระบบบริหารคุณภาพ",
    Item_ID: "9.1.4",
    Criteria_Detail: "4.ผลการทบทวนการบริหารความเสี่ยงในหน่วยงาน (risk management)",
    Success_Indicator: "",
    Status: "🔴 ยังไม่พร้อม",
    Responsible_Person: "",
    Evidence_Link: [],
    Auditor_Comment: "",
    Last_Update: ""
  }
];
